name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted  # Use self-hosted runner
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          sudo docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest .

      - name: Tag Docker image
        run: |
          sudo docker tag ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
      
      - name: Push Docker image to Docker Hub
        run: |
          sudo docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
          sudo docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest

      - name: Deploy Docker container
        run: |
          # Stop and remove existing Docker container
          sudo docker stop my-app-container || true
          sudo docker rm my-app-container || true

          # Pull the latest image from Docker Hub
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest

          # Run the new container on port 3000
          sudo docker run -d -p 3000:3000 --name my-app-container ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest

          - name: Set up Nginx for port forwarding (only run first time)
          run: |
            if ! grep -q "proxy_pass http://localhost:3000;" /etc/nginx/sites-available/default; then
              sudo tee /etc/nginx/sites-available/default <<EOL
              server {
                listen 80;
                server_name _;
        
                location / {
                  proxy_pass http://localhost:3000;
                  proxy_set_header Host \$host;
                  proxy_set_header X-Real-IP \$remote_addr;
                  proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto \$scheme;
                }
              }
              EOL
        
              # Restart Nginx to apply the changes
              sudo systemctl restart nginx
            else
              echo "Nginx is already set up. Skipping Nginx configuration."
            fi
        

          # Restart Nginx to apply the changes-
          sudo systemctl restart nginx
